// GENERATED by zpi codegen — do not edit.
// source: https://api.zpi.web.id
// regenerate with: npx zpi codegen --scan . --out ./src/zpi.d.ts

/** Pass to `client.useMethods(ZPI_METHODS)` so no call has to discover its verb. */
export const ZPI_METHODS: Record<string, Record<string, "GET" | "POST">> = {
	"temp-mail:mail-gw": { create: "GET", inbox: "GET" },
};

declare module "zpi-sdk" {
	interface ScraperMap {
		"temp-mail:mail-gw": { create: { params: Record<string, unknown> }; inbox: { params: { /** The disposable address to read (as returned by create). */ address: string; } }; };
	}
}
